Presentation/Nop.Web/Controllers/CatalogController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Catalog;
using Nop.Core.Domain.Customers;
using Nop.Core.Domain.Media;
using Nop.Core.Domain.Vendors;
using Nop.Services.Catalog;
using Nop.Services.Common;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Security;
using Nop.Services.Stores;
using Nop.Services.Vendors;
using Nop.Web.Factories;
using Nop.Web.Framework;
using Nop.Web.Framework.Mvc.Filters;
using Nop.Web.Framework.Security;
using Nop.Web.Models.Catalog;
using System.Collections.Generic;

namespace Nop.Web.Controllers
{
    public partial class CatalogController : BasePublicController
    {
        #region Fields

        private readonly CatalogSettings _catalogSettings;
        private readonly IAclService _aclService;
        private readonly ICatalogModelFactory _catalogModelFactory;
        private readonly ICategoryService _categoryService;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly IGenericAttributeService _genericAttributeService;
        private readonly ILocalizationService _localizationService;
        private readonly IManufacturerService _manufacturerService;
        private readonly IPermissionService _permissionService;
        private readonly IProductModelFactory _productModelFactory;
        private readonly IProductService _productService;
        private readonly IProductTagService _productTagService;
        private readonly IStoreContext _storeContext;
        private readonly IStoreMappingService _storeMappingService;
        private readonly IVendorService _vendorService;
        private readonly IWebHelper _webHelper;
        private readonly IWorkContext _workContext;
        private readonly MediaSettings _mediaSettings;
        private readonly VendorSettings _vendorSettings;

        #endregion

        #region Ctor

        public CatalogController(CatalogSettings catalogSettings,
            IAclService aclService,
            ICatalogModelFactory catalogModelFactory,
            ICategoryService categoryService, 
            ICustomerActivityService customerActivityService,
            IGenericAttributeService genericAttributeService,
            ILocalizationService localizationService,
            IManufacturerService manufacturerService,
            IPermissionService permissionService, 
            IProductModelFactory productModelFactory,
            IProductService productService, 
            IProductTagService productTagService,
            IStoreContext storeContext,
            IStoreMappingService storeMappingService,
            IVendorService vendorService,
            IWebHelper webHelper,
            IWorkContext workContext, 
            MediaSettings mediaSettings,
            VendorSettings vendorSettings)
        {
            this._catalogSettings = catalogSettings;
            this._aclService = aclService;
            this._catalogModelFactory = catalogModelFactory;
            this._categoryService = categoryService;
            this._customerActivityService = customerActivityService;
            this._genericAttributeService = genericAttributeService;
            this._localizationService = localizationService;
            this._manufacturerService = manufacturerService;
            this._permissionService = permissionService;
            this._productModelFactory = productModelFactory;
            this._productService = productService;
            this._productTagService = productTagService;
            this._storeContext = storeContext;
            this._storeMappingService = storeMappingService;
            this._vendorService = vendorService;
            this._webHelper = webHelper;
            this._workContext = workContext;
            this._mediaSettings = mediaSettings;
            this._vendorSettings = vendorSettings;
        }

        #endregion
        
        #region Categories
        
        [HttpsRequirement(SslRequirement.No)]
        public virtual IActionResult Category(int categoryId, CatalogPagingFilteringModel command)
        {
            var category = _categoryService.GetCategoryById(categoryId);
            if (category == null || category.Deleted)
                return InvokeHttp404();

            var notAvailable =
                //published?
                !category.Published ||
                //ACL (access control list) 
                !_aclService.Authorize(category) ||
                //Store mapping
                !_storeMappingService.Authorize(category);
            //Check whether the current user has a "Manage categories" permission (usually a store owner)
            //We should allows him (her) to use "Preview" functionality
            if (notAvailable && !_permissionService.Authorize(StandardPermissionProvider.ManageCategories))
                return InvokeHttp404();

            //'Continue shopping' URL
            _genericAttributeService.SaveAttribute(_workContext.CurrentCustomer, 
                NopCustomerDefaults.LastContinueShoppingPageAttribute, 
                _webHelper.GetThisPageUrl(false),
                _storeContext.CurrentStore.Id);

            //display "edit" (manage) link
            if (_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel) && _permissionService.Authorize(StandardPermissionProvider.ManageCategories))
                DisplayEditLink(Url.Action("Edit", "Category", new { id = category.Id, area = AreaNames.Admin }));

            //activity log
            _customerActivityService.InsertActivity("PublicStore.ViewCategory",
                string.Format(_localizationService.GetResource("ActivityLog.PublicStore.ViewCategory"), category.Name), category);

            //model
            var model = _catalogModelFactory.PreparePartyramaCategoryModel(category);

            //template
            var templateViewPath = _catalogModelFactory.PrepareCategoryTemplateViewPath(category.CategoryTemplateId);
            return View(templateViewPath, model);
        }

        #endregion

        #region Manufacturers

        [HttpsRequirement(SslRequirement.No)]
        public virtual IActionResult Manufacturer(int manufacturerId, CatalogPagingFilteringModel command)
        {
            var manufacturer = _manufacturerService.GetManufacturerById(manufacturerId);
            if (manufacturer == null || manufacturer.Deleted)
                return InvokeHttp404();

            var notAvailable =
                //published?
                !manufacturer.Published ||
                //ACL (access control list) 
                !_aclService.Authorize(manufacturer) ||
                //Store mapping
                !_storeMappingService.Authorize(manufacturer);
            //Check whether the current user has a "Manage categories" permission (usually a store owner)
            //We should allows him (her) to use "Preview" functionality
            if (notAvailable && !_permissionService.Authorize(StandardPermissionProvider.ManageManufacturers))
                return InvokeHttp404();

            //'Continue shopping' URL
            _genericAttributeService.SaveAttribute(_workContext.CurrentCustomer, 
                NopCustomerDefaults.LastContinueShoppingPageAttribute, 
                _webHelper.GetThisPageUrl(false),
                _storeContext.CurrentStore.Id);
            
            //display "edit" (manage) link
            if (_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel) && _permissionService.Authorize(StandardPermissionProvider.ManageManufacturers))
                DisplayEditLink(Url.Action("Edit", "Manufacturer", new { id = manufacturer.Id, area = AreaNames.Admin }));

            //activity log
            _customerActivityService.InsertActivity("PublicStore.ViewManufacturer",
                string.Format(_localizationService.GetResource("ActivityLog.PublicStore.ViewManufacturer"), manufacturer.Name), manufacturer);

            //model
            var model = _catalogModelFactory.PrepareManufacturerModel(manufacturer, command);
            
            //template
            var templateViewPath = _catalogModelFactory.PrepareManufacturerTemplateViewPath(manufacturer.ManufacturerTemplateId);
            return View(templateViewPath, model);
        }

        [HttpsRequirement(SslRequirement.No)]
        public virtual IActionResult ManufacturerAll()
        {
            var model = _catalogModelFactory.PrepareManufacturerAllModels();
            return View(model);
        }
        
        #endregion

        #region Vendors

        [HttpsRequirement(SslRequirement.No)]
        public virtual IActionResult Vendor(int vendorId, CatalogPagingFilteringModel command)
        {
            var vendor = _vendorService.GetVendorById(vendorId);
            if (vendor == null || vendor.Deleted || !vendor.Active)
                return InvokeHttp404();

            //'Continue shopping' URL
            _genericAttributeService.SaveAttribute(_workContext.CurrentCustomer,
                NopCustomerDefaults.LastContinueShoppingPageAttribute,
                _webHelper.GetThisPageUrl(false),
                _storeContext.CurrentStore.Id);
            
            //display "edit" (manage) link
            if (_permissionService.Authorize(StandardPermissionProvider.AccessAdminPanel) && _permissionService.Authorize(StandardPermissionProvider.ManageVendors))
                DisplayEditLink(Url.Action("Edit", "Vendor", new { id = vendor.Id, area = AreaNames.Admin }));

            //model
            var model = _catalogModelFactory.PrepareVendorModel(vendor, command);

            return View(model);
        }

        [HttpsRequirement(SslRequirement.No)]
        public virtual IActionResult VendorAll()
        {
            //we don't allow viewing of vendors if "vendors" block is hidden
            if (_vendorSettings.VendorsBlockItemsToDisplay == 0)

Presentation/Nop.Web/Areas/Admin/Views/Sidebar/SidebarAddRowCategoryPopup.cshtml
@model SidebarAddRowCategorySearchModel

@{
    Layout = "_AdminPopupLayout";

    //page title
    ViewBag.Title = T("Admin.Catalog.Item.AddCategoryRow").Text;
}

<form asp-controller="Sidebar" asp-action="SidebarAddRowCategoryPopup"
      asp-route-sidebarId="@Context.Request.Query["sidebarId"]"
      asp-route-btnId="@Context.Request.Query["btnId"]">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.Catalog.Item.AddCategoryRow")
        </h1>
        <div class="pull-right">
            &nbsp;
        </div>
    </div>

    @if (ViewBag.RefreshPage == true)
    {
    <script>
            try {window.opener.document.getElementById('@(Context.Request.Query["btnId"].ToString())').click();}
            catch (e){}
            window.close();
    </script>
    }

    <div class="content">
        <div class="form-horizontal">
            <div class="panel-group">
                <div class="panel panel-default panel-popup">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-8">
                                <div class="form-group">
                                    <div class="col-sm-4">
                                        <nop-label asp-for="SidebarItemId" />
                                    </div>
                                    <div class="col-sm-8">
                                        <nop-select asp-for="SidebarItemId" asp-items="Model.AvailableColumns" />
                                        <span asp-validation-for="SidebarItemId"></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default panel-search panel-popup">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-sm-8">
                                <div class="form-group">
                                    <div class="col-sm-4">
                                        <nop-label asp-for="SearchCategoryName" />
                                    </div>
                                    <div class="col-sm-8">
                                        <nop-editor asp-for="SearchCategoryName" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-8 col-sm-offset-4">
                                        <button type="button" id="search-categories" class="btn btn-primary btn-search">@T("Admin.Common.Search")</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div id="categories-grid"></div>

                        <script>
                            $(document).ready(function () {
                                $("#categories-grid").kendoGrid({
                                    dataSource: {
                                        type: "json",
                                        transport: {
                                            read: {
                                                url: "@Html.Raw(Url.Action("RowCategoryAddPopupList", "Sidebar"))",
                                                type: "POST",
                                                dataType: "json",
                                                data: function() {
                                                    var data = {
                                                        SearchCategoryName: $('#@Html.IdFor(model => model.SearchCategoryName)').val()
                                                    };
                                                    addAntiForgeryToken(data);
                                                    return data;
                                                }
                                            }
                                        },
                                        schema: {
                                            data: "Data",
                                            total: "Total",
                                            errors: "Errors"
                                        },
                                        error: function(e) {
                                            display_kendoui_grid_error(e);
                                            // Cancel the changes
                                            this.cancelChanges();
                                        },
                                        pageSize: @(Model.PageSize),
                                        serverPaging: true,
                                        serverFiltering: true,
                                        serverSorting: true
                                    },
                                    pageable: {
                                        refresh: true,
                                        pageSizes: [@(Model.AvailablePageSizes)],
                                        @await Html.PartialAsync("_GridPagerMessages")
                                    },
                                    editable: {
                                        confirmation: "@T("Admin.Common.DeleteConfirmation")",
                                        mode: "inline"
                                    },
                                    scrollable: false,
                                    columns: [{
                                        field: "Id",
                                        headerTemplate: "<input id='mastercheckbox' type='checkbox'/>",
                                        headerAttributes: { style: "text-align:center" },
                                        template: "<input type='checkbox' name='SelectedCategoryIds' value='#=Id#' class='checkboxGroups' />",
                                        attributes: { style: "text-align:center" },
                                        width: 50
                                    }, {
                                        field: "Breadcrumb",
                                        title: "@T("Admin.Catalog.Categories.Fields.Name")"
                                    }, {
                                        field: "Published",
                                        title: "@T("Admin.Catalog.Categories.Fields.Published")",
                                        width: 100,
                                        headerAttributes: { style: "text-align:center" },
                                        attributes: { style: "text-align:center" },
                                        template: '# if(Published) {# <i class="fa fa-check true-icon"></i> #} else {# <i class="fa fa-close false-icon"></i> #} #'
                                    }]
                                });
                            });
                        </script>

                        <script>
                            $(document).ready(function() {
                                $('#search-categories').click(function() {
                                    var grid = $('#categories-grid').data('kendoGrid');
                                    grid.dataSource.page(1); //new search. Set page size to 1
                                    //grid.dataSource.read(); we already loaded the grid above using "page" function
                                    //clear selected checkboxes
                                    $('.checkboxGroups').attr('checked', false).change();
                                    return false;
                                });

                                $("#@Html.IdFor(model => model.SearchCategoryName)").keydown(function(event) {
                                    if (event.keyCode == 13) {
                                        $("#search-categories").click();
                                        return false;
                                    }
                                });

                                //wire up checkboxes
                                $('#mastercheckbox').click(function() {
                                    $('.checkboxGroups').attr('checked', $(this).is(':checked')).change();
                                });

                                $('#categories-grid').on('change', 'input[type=checkbox][id!=mastercheckbox][class=checkboxGroups]', function(e) {
                                    updateMasterCheckbox();
                                });
                            });

                            function updateMasterCheckbox() {
                                var numChkBoxes = $('#categories-grid input[type=checkbox][id!=mastercheckbox][class=checkboxGroups]').length;
                                var numChkBoxesChecked = $('#categories-grid input[type=checkbox][id!=mastercheckbox][class=checkboxGroups]:checked').length;
                                $('#mastercheckbox').attr('checked', numChkBoxes == numChkBoxesChecked && numChkBoxes > 0);
                            }

                        </script>
                    </div>
                    <div class="panel-footer">
                        <button type="submit" name="save" class="btn bg-blue">
                            <i class="fa fa-floppy-o"></i>
                            @T("Admin.Common.Save")
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Presentation/Nop.Web/Areas/Admin/Views/Sidebar/_SidebarEdit.cshtml
@model SidebarModel

<div class="panel panel-default" style="min-height: 100px;">
    <div class="panel-heading" id="sidebarHdr">
        @Model.Name
    </div>
    <div class="panel-body">
        <div class="buttons">
            <button id="btnSidebarSettings" class="btn btn-info"><i class="fa fa-gear"></i>Settings</button>
            <button id="btnSidebarPreview" type="button" class="btn bg-purple">
                <i class="fa fa-eye"></i>
                Preview
            </button>
            <div id="previewWindow">
                @{await Html.RenderPartialAsync("_SidebarPreview");}
            </div>
        </div>
        <form asp-controller="Sidebar" asp-action="EditSidebar" method="post" id="sidebarEditForm" style="display: none;">
            <div class="form-group">
                <div class="col-sm-3">
                    <nop-label asp-for="Name" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="Name" />
                    <span asp-validation-for="Name"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="SetCountDown" />
                </div>
                <div class="col-md-9">
                    <nop-editor asp-for="SetCountDown" />
                    <span asp-validation-for="SetCountDown"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="Visible" />
                </div>
                <div class="col-md-9">
                    <nop-editor asp-for="Visible" />
                    <span asp-validation-for="Visible"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-3">
                    <nop-label asp-for="StartDateUtc" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="StartDateUtc" />
                    <span asp-validation-for="StartDateUtc"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-3">
                    <nop-label asp-for="EndDateUtc" />
                </div>
                <div class="col-sm-9">
                    <nop-editor asp-for="EndDateUtc" />
                    <span asp-validation-for="EndDateUtc"></span>
                </div>
            </div>
            <div class="buttons" id="divActionButtons">
                <button id="btnSaveSidebar" class="btn bg-blue"><i class="fa fa-floppy-o"></i>Save</button>
                <button id="btnCancelSidebar" class="btn">Cancel</button>
                <button id="btnSidebarDelete" type="button" onclick="DeleteSidebar(@Model.Id)" class="btn bg-red pull-right"><i class="fa fa-trash-o"></i>Delete</button>
            </div>
        </form>
        <div id="itemButtons" class="buttons margin-t-5">
            <button id="btnSidebarAddHeader" class="btn btn-primary" onclick="AddColumn(@Model.Id, '@Nop.Core.Domain.Catalog.RowType.header')">@T("Admin.Catalog.AddHeader")</button>
            <button id="btnSidebarAddTextColumn" class="btn btn-primary" onclick="AddColumn(@Model.Id, '@Nop.Core.Domain.Catalog.RowType.textcolumn')">@T("Admin.Catalog.AddTextColumn")</button>
            <button id="btnSidebarAddImageColumn" class="btn btn-primary" onclick="AddColumn(@Model.Id, '@Nop.Core.Domain.Catalog.RowType.imagecolumn')">@T("Admin.Catalog.AddImageColumn")</button>
            <button id="btnAddCategoryRow"
                    onclick="javascript:OpenWindow('@(Url.Action("SidebarAddRowCategoryPopup", "Sidebar", new { sidebarId = Model.Id, btnId = "btnRefreshItems" }))', 800, 800, true); return false;"
                    class="btn btn-primary">
                @T("Admin.Catalog.Item.AddCategoryRow")
            </button>
            <button id="btnAddProductRow"
                    onclick="javascript:OpenWindow('@(Url.Action("SidebarAddRowProductPopup", "Sidebar", new { sidebarId = Model.Id, btnId = "btnRefreshItems" }))', 800, 800, true); return false;"
                    class="btn btn-primary">
                @T("Admin.Catalog.Item.AddProductRow")
            </button>
            <button id="btnAddElementRow"
                    onclick="javascript:OpenWindow('@(Url.Action("SidebarAddRowElementPopup", "Sidebar", new { sidebarId = Model.Id, btnId = "btnRefreshItems" }))', 800, 800, true); return false;"
                    class="btn btn-primary">
                @T("Admin.Catalog.Item.AddElementRow")
            </button>
            <button id="btnAddTopicRow"
                    onclick="javascript:OpenWindow('@(Url.Action("SidebarAddRowTopicPopup", "Sidebar", new { sidebarId = Model.Id, btnId = "btnRefreshItems" }))', 800, 800, true); return false;"
                    class="btn btn-primary">
                @T("Admin.Catalog.Item.AddTopicRow")
            </button>
            <button id="btnAddSidebarRow"
                    onclick="javascript:OpenWindow('@(Url.Action("SidebarAddRowSliderPopup", "Sidebar", new { sidebarId = Model.Id, btnId = "btnRefreshItems" }))', 800, 800, true); return false;"
                    class="btn btn-primary">
                @T("Admin.Catalog.Item.AddSliderRow")
            </button>
        </div>
        <div id="addColumnBox" class="margin-t-5"></div>
    </div>
</div>

<script>
    var sidebarViewModel = kendo.observable({
        Items: {}
    });

    var previewWindow = $("#previewWindow"),
        btnSidebarPreview = $("#btnSidebarPreview");

    previewWindow.kendoWindow({
        width: "960px",
        visible: false,
        title: '@Model.Name'
    });

    btnSidebarPreview.click(function () {
        $.ajax({
            type: 'GET',
            url: "@Html.Raw(Url.Action("SidebarPreview", "Catalog", new { Area = "" }))",
            data: {  SidebarId: '@Model.Id' },
            success: function (data) {
                if (data.Items.length > 0) {
                    sidebarViewModel.set('Items', data.Items);
                    kendo.bind(previewWindow, sidebarViewModel);
                }

                var modal = previewWindow.data("kendoWindow");
                previewWindow.data("kendoWindow").open().center();
                PreviewInit();
            }
        });

        return false;
    });

    $('#btnSidebarSettings').on('click', function (e) {
        $("#sidebarEditForm").show();
        $(this).hide();
        $("#divActionButtons").show();
    });

    $('#btnSaveSidebar').on('click', function (e) {
        e.preventDefault();
        e.stopPropagation();

        var form = $('#sidebarEditForm');
        $.validator.unobtrusive.parse(form);
        form.validate();

        if (form.valid()) {
            $.ajax({
            cache: false,
            url: "@(Url.Action("EditSidebar", "Sidebar"))",
            data: form.serialize(),
            type: 'post',
            success: function (response) {
                if (response.success) {
                    $('#sidebarHdr').text(response.name);
                    $('#sidebarDetails_@Model.Id').text(response.name);
                } else {
                    alert(response.message);
                }
            },
            error: function() {
                alert('Failed to add the sidebar. Please refresh the page and try one more time.');
            }
        });

        }
    });

    $('#btnCancelSidebar').on('click', function (e) {
        e.preventDefault();
        e.stopPropagation();

        $("#sidebarEditForm").hide();
        $("#btnSidebarSettings").show();
        $("#divActionButtons").hide();
    });

    function PreviewInit() {
        $(".sd_column_title").on('click', function () {
            var element = $(this).parent('.sd_col');
            if (element.hasClass('open')) {
                element.removeClass('open');
                element.children('.sd_row').slideUp();
            } else {
                element.addClass('open');
                element.children('.sd_row').slideDown();
                var siblings = element.siblings('.sd_col');
                siblings.children('.sd_row').slideUp();
                siblings.removeClass('open');
                siblings.children('.sd_row').slideUp();
            }
        });
    };
</script>